config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :todos

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  def mark_as_done
    self.done = true
    self.save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

  def index
    @todos = Todo.all
  end

  def show
    set_a_todo
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.create(todo_params)
    redirect_to todo_path(@todo)
  end

  def edit
    set_a_todo
  end

  def update
    set_a_todo
    @todo.update(todo_params)
    redirect_to todo_path(@todo)
  end

  def destroy
    set_a_todo
    @todo.destroy
    redirect_to todos_path
  end


  private
  def set_a_todo
    @todo = Todo.find(params[:id])
  end

  def todo_params
    params.require(:todo).permit(:name, :description, :done)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_for @todo, class: '', id: '' do |f| %>
  <%= f.label :name, 'Name' %>
  <%= f.text_field :name, class: 'text' %>
  <%= f.label :description, 'Description' %>
  <%= f.text_field :description %>
  <%= f.label :done, 'Is it done?' %>
  <%= f.check_box :done %>
  <%= f.submit wording %>
<% end %>

app/views/todos/edit.html.erb
<h1>Edit the task bitch!</h1>

<%= render 'form', wording: "Save task" %>

app/views/todos/index.html.erb
<h2>Awesome TODO list</h2>

    <%= link_to 'Create task', new_todo_path %>



  <% @todos.each do |todo| %>
    <p><%= todo.name %></p>
    <p><%= todo.description %></p>
    <p><%= todo.done %></p>
    <%= link_to 'Look at the task', todo_path(todo) %>
    <%= link_to 'Edit the task', edit_todo_path(todo) %>
<%end%>




<!--
Should display a list of all tasks and, for each task:
a link to its show view (use a link_to helper)
a link to its edit view
a link to its delete action. Hint: a standard link does not allow to perform DELETE request, so here you should add a method: :delete option to your link_to helper.
Should include a link to the new view to create a new task -->

app/views/todos/new.html.erb
<h1>Make a fucking new task and stick to it bitch</h1>

<%= render 'form', wording: "Create new task" %>

app/views/todos/show.html.erb
<h1><%= @todo.name %></h1>
<h2><%= @todo.description %></h2>
<h2><%= @todo.done %></h2>
<%= link_to 'Go back bitch', todos_path %>
<%= link_to 'Delete this task', todo_path(@todo), method: :delete %>
<h2><%= @todo.created_at.strftime("at %H:%M, %b %d, %Y") %></h2>